# Generated by Django 4.2.7 on 2025-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('categorie', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Base de données'), ('devops', 'DevOps'), ('design', 'Design'), ('ia', 'Intelligence Artificielle'), ('autres', 'Autres')], max_length=20, verbose_name='Catégorie')),
                ('niveau', models.IntegerField(default=50, help_text='Niveau de maîtrise en pourcentage (0-100)', verbose_name='Niveau (%)')),
                ('icone', models.CharField(blank=True, help_text="Classe CSS pour l'icône (ex: fab fa-python)", max_length=100)),
                ('couleur', models.CharField(default='#007bff', help_text='Couleur en hexadécimal (ex: #FF5733)', max_length=7)),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Compétence active')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet du message')),
                ('message', models.TextField(verbose_name='Message')),
                ('envoye_le', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('lu', models.BooleanField(default=False, verbose_name='Message lu')),
                ('repondu', models.BooleanField(default=False, verbose_name='Réponse envoyée')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('titre', models.CharField(default='Développeur Full Stack', max_length=200, verbose_name='Titre professionnel')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('bio', models.TextField(help_text='Description courte de votre parcours', verbose_name='Biographie')),
                ('description_longue', models.TextField(help_text='Description complète de vos compétences', verbose_name='Description détaillée')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Photo de profil')),
                ('cv', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='CV (PDF)')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('website', models.URLField(blank=True, verbose_name='Site web personnel')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('actif', models.BooleanField(default=True, verbose_name='Profil actif')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description_courte', models.CharField(max_length=300, verbose_name='Description courte')),
                ('description_longue', models.TextField(verbose_name='Description détaillée')),
                ('image_principale', models.ImageField(upload_to='projects/', verbose_name='Image principale')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image secondaire')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image tertiaire')),
                ('url_demo', models.URLField(blank=True, verbose_name='URL de démonstration')),
                ('url_code', models.URLField(blank=True, verbose_name='URL du code source')),
                ('url_case_study', models.URLField(blank=True, verbose_name='Étude de cas')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('pause', 'En pause'), ('archive', 'Archivé')], default='termine', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('featured', models.BooleanField(default=False, verbose_name='Projet mis en avant')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Projet actif')),
                ('technologies', models.ManyToManyField(help_text='Sélectionnez les compétences utilisées', to='portfolio.competence', verbose_name='Technologies utilisées')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-featured', 'ordre', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_experience', models.CharField(choices=[('travail', 'Expérience professionnelle'), ('formation', 'Formation'), ('projet', 'Projet personnel'), ('benevolat', 'Bénévolat')], max_length=20, verbose_name="Type d'expérience")),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du poste/formation')),
                ('entreprise', models.CharField(max_length=200, verbose_name='Entreprise/École')),
                ('lieu', models.CharField(blank=True, max_length=100, verbose_name='Lieu')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin (laisser vide si en cours)')),
                ('description', models.TextField(verbose_name='Description des tâches/apprentissages')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Expérience active')),
                ('competences_acquises', models.ManyToManyField(blank=True, to='portfolio.competence', verbose_name='Compétences acquises')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-date_debut'],
            },
        ),
    ]
